version: "3.8"
services:
    nodeserver:
        image: jakubblockczech/test
        ports:
            - "8000:8000"
        volumes:
            - my_db_volume:/node/db
    nginx:
        image: jakubblockczech/nginx
        restart: always
        ports:
            - "80:80"
volumes:
  my_db_volume:
    driver: local
    driver_opts:
       o: bind
       type: none
       device: /mnt/node/db
