# This is a basic workflow to help you get started with Actions

name: CI/CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "Upload env"
  build:
    name: Build and Deploy
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build nginx
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: jakubblockczech/nginx:latest
        context: nginx/.
    - name: Build node backend
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: jakubblockczech/test:latest
        context: .
    - name: Move docker-compose.yml to server
      env:
        PRIVATE_KEY: ${{ secrets.SSH_KEY  }}
        HOSTNAME: ${{ secrets.SSH_HOST  }}
        USER_NAME: ${{ secrets.SSH_USERNAME  }}
      run: |
        echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
        scp -o StrictHostKeyChecking=no -i private_key docker-compose.yml ${USER_NAME}@${HOSTNAME}:
    - name: Create directory for source code on the server
      env:
        PRIVATE_KEY: ${{ secrets.SSH_KEY  }}
        HOSTNAME: ${{ secrets.SSH_HOST  }}
        USER_NAME: ${{ secrets.SSH_USERNAME  }}
      run: |
        echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
        ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
            [ -d "/opt/app/" ] && rm -rf /opt/app/ || echo 0
            mkdir /opt/app/
        '
    - name: Copy src to server
      env:
        PRIVATE_KEY: ${{ secrets.SSH_KEY  }}
        HOSTNAME: ${{ secrets.SSH_HOST  }}
        USER_NAME: ${{ secrets.SSH_USERNAME  }}
      run: |
        echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
        scp -r -o StrictHostKeyChecking=no -i private_key ${GITHUB_WORKSPACE}/* ${USER_NAME}@${HOSTNAME}:/opt/app/
    - name: Run docker image on the server
      env:
        PRIVATE_KEY: ${{ secrets.SSH_KEY  }}
        HOSTNAME : ${{ secrets.SSH_HOST  }}
        USER_NAME : ${{ secrets.SSH_USERNAME  }}
      run: |
        echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
        ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
          echo PULLING DOCKER IMAGE NGINX
          docker pull jakubblockczech/nginx
          echo PULLING DOCKER IMAGE NODE APP
          docker pull jakubblockczech/test
          echo STOPPING PREVIOUS DOCKER CONTAINERS
          docker-compose down
          echo RUNNING NEW DOCKER INSTANCE
          docker-compose up -d
          '
